### ISSUE TITLE
Firefox unresponsive when hosting site locally

### ISSUE THREAD

**Issue by CameronMcWilliam** [Kitura/kitura.io#408]
When running gatsby develop on site locally, Firefox is unresponsive and cannot be used.  This can pose a problem for people looking to contribute to the site, who primarily use Firefox.

**Comment by sxa555** [comment]
If I view kituro.io on Firefox it is unresponsive until FireFox pops up a banner asking if you want to stop the page from slowing down my browser.
![image](https://user-images.githubusercontent.com/6487691/69742453-b6bc8080-1134-11ea-9740-50bee211f774.png)

**Comment by andrewhughes101** [comment]
+1 on @sxa555 comment, the site also seems to have some weird behaviour when clicking on the buttons that seem unresponsive but then open the links when you navigate away from the kitura.io site in the same tab

**Comment by ddunn2** [comment]
This issue should be resolved by this PR: https://github.com/Kitura/kitura.io/pull/451
