### ISSUE TITLE
Some scripts on the site make Firefox on Linux hang

### ISSUE THREAD

**Issue by gabriel-fallen** [Kitura/kitura.io#444]
When I open any page of the site in Firefox on Linux it hangs for a while and then shows a message that some scripts make it unresponsive. If I choose to stop the scripts everything works fine until I navigate to another page, then the whole thing starts again.

Could you maybe remove some unnecessary scripts please?

**Comment by ddunn2** [comment]
This issue should be resolved with this PR: https://github.com/Kitura/kitura.io/pull/451
